name: Build and Test
on:
  pull_request:
    paths-ignore:
      - dist/*
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag Name'
        required: true
        default: 'dev'
        type: choice
        options:
          - 'dev'
          - 'stable'

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:20
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: npm install
        run: npm install
      
      - name: npm run build
        run: npm run build
      
      - name: npm run test
        run: npm run test || echo "Tests not yet implemented"
      
      - name: Commit and Push
        if: github.event_name == 'pull_request'
        run: |
          git config --global user.email ${{ github.actor }}@users.noreply.github.com
          git config --global user.name "github-actions[bot]"
          git config --global --add safe.directory /__w/github-action-container-job/github-action-container-job
          
          if [ -z "$(git status --porcelain)" ]; then
            echo "changed=0">> $GITHUB_OUTPUT
            echo "No changes"
            exit 0
          fi
          
          echo "changed=1">> $GITHUB_OUTPUT
          git add -A
          git commit -m "Build Release"
          git push || echo "Push skipped (no permission or already up to date)"

      - name: Create tag
        if: github.event_name != 'pull_request'
        uses: actions/github-script@v7
        with:
          script: |
            try {
              await github.rest.git.updateRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            } catch (err) {
              console.log(err)

              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref: 'refs/tags/${{ github.event.inputs.tag }}',
                sha: context.sha,
              })
            }